### ISSUE TITLE
How to handle files without-linter

### ISSUE THREAD

**Issue by santiagotoscanini** [mfussenegger/nvim-lint#135] opened 2021-12-13 04:17 UTC
Hi,

I have the following setting in my `init.vim`:
```vim
au BufWritePost <buffer> lua require('lint').try_lint()
```

And I have the following configuration for `nvim-lint`:
```lua
require('lint').linters_by_ft = {
    python = {'flake8'},
    vim = {'vint'},
    lua = {'luacheck'},
}
```

So whenever I save a buffer, I get the hints from the linters, and it's working perfectly!

But I wonder how I can handle the case of non-linted files, like languages without linting configured. Is there something like:
```lua
require('lint').linters_by_ft = {
    ... -- python, vim, lua, etc.
    all = {}
}
```

I know I could simply add a shortcut and trigger the linting on the supported file types, but I want to keep the "on save" flow.

**Comment by mfussenegger** [comment] 2021-12-13 12:07
> But I wonder how I can handle the case of non-linted files, like languages without linting configured. Is there something like:

I suspect you hit a recent regression that got fixed in https://github.com/mfussenegger/nvim-lint/pull/137
There is no `all` because it shouldn't be needed.  `try_lint` was supposed to do nothing if there is no configured linter

**Comment by santiagotoscanini** [comment] 2021-12-13 13:01
You're right, now it works,

Thanks!

**Closed** 2021-12-13 13:01 UTC
